# Generated by Django 5.2.8 on 2025-11-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponible', models.BooleanField(default=True)),
                ('tiempo_preparacion_min', models.IntegerField()),
                ('calorias', models.IntegerField()),
                ('es_vegetariano', models.BooleanField(default=False)),
                ('nivel_picante', models.IntegerField(choices=[(0, 'Sin picante'), (1, 'Suave'), (2, 'Medio'), (3, 'Alto')], default=0)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
    ]
